CREATE DATABASE wildlife_tracker;

\c wildlife_tracker;

CREATE TABLE animals(
id Int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR,
age VARCHAR,
behaviour VARCHAR,
health VARCHAR,
risk VARCHAR
);

CREATE TABLE location(
id Int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
type VARCHAR,
time TIMESTAMP
);

CREATE TABLE ranger(
id Int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
rangerName VARCHAR,
radioTelephoneFrequency VARCHAR,
avatarUrl VARCHAR,
badgeNumber VARCHAR
);

CREATE TABLE sightings(
id Int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
animalname VARCHAR,
animaltype VARCHAR,
location VARCHAR,
rangername VARCHAR,
time TIMESTAMP
);



CREATE DATABASE wildlife_tracker_test WITH TEMPLATE wildlife_tracker;